# Generated by Django 4.2.23 on 2025-07-04 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='凭据名称')),
                ('credential_type', models.CharField(choices=[('ssh_key', 'SSH密钥'), ('password', '用户名密码'), ('vault', 'Ansible Vault')], max_length=20, verbose_name='凭据类型')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='用户名')),
                ('password', models.TextField(blank=True, verbose_name='密码')),
                ('ssh_private_key', models.TextField(blank=True, verbose_name='SSH私钥')),
                ('vault_password', models.TextField(blank=True, verbose_name='Vault密码')),
                ('sudo_password', models.TextField(blank=True, verbose_name='Sudo密码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'Ansible凭据',
                'verbose_name_plural': 'Ansible凭据',
                'db_table': 'ansible_credential',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnsiblePlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Playbook名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('content', models.TextField(verbose_name='Playbook内容')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='版本')),
                ('is_template', models.BooleanField(default=False, verbose_name='是否为模板')),
                ('category', models.CharField(choices=[('web', 'Web应用'), ('database', '数据库'), ('monitoring', '监控'), ('security', '安全'), ('networking', '网络'), ('system', '系统'), ('other', '其他')], default='other', max_length=50, verbose_name='分类')),
                ('parameters', models.JSONField(default=dict, verbose_name='可配置参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'Ansible Playbook',
                'verbose_name_plural': 'Ansible Playbooks',
                'db_table': 'ansible_playbook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnsibleInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='清单名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('content', models.TextField(verbose_name='清单内容')),
                ('format_type', models.CharField(choices=[('ini', 'INI格式'), ('yaml', 'YAML格式')], default='ini', max_length=10, verbose_name='格式类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'Ansible主机清单',
                'verbose_name_plural': 'Ansible主机清单',
                'db_table': 'ansible_inventory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnsibleExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict, verbose_name='执行参数')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('stdout', models.TextField(blank=True, verbose_name='标准输出')),
                ('stderr', models.TextField(blank=True, verbose_name='错误输出')),
                ('return_code', models.IntegerField(blank=True, null=True, verbose_name='返回码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_integration.ansiblecredential', verbose_name='认证凭据')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_integration.ansibleinventory', verbose_name='主机清单')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_integration.ansibleplaybook', verbose_name='Playbook')),
            ],
            options={
                'verbose_name': 'Ansible执行记录',
                'verbose_name_plural': 'Ansible执行记录',
                'db_table': 'ansible_execution',
                'ordering': ['-created_at'],
            },
        ),
    ]
