# Generated by Django 4.2.23 on 2025-07-04 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_pipeline_execution_mode_pipeline_execution_tool_and_more'),
        ('ansible_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibleexecution',
            name='pipeline',
            field=models.ForeignKey(blank=True, help_text='如果此Ansible执行是流水线的一部分', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ansible_executions', to='pipelines.pipeline', verbose_name='关联流水线'),
        ),
        migrations.AddField(
            model_name='ansibleexecution',
            name='pipeline_step',
            field=models.ForeignKey(blank=True, help_text='如果此Ansible执行对应特定的流水线步骤', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ansible_executions', to='pipelines.pipelinestep', verbose_name='关联流水线步骤'),
        ),
    ]
