# Generated by Django 4.2.23 on 2025-07-09 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ansible_integration', '0002_ansibleexecution_pipeline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('tags', models.JSONField(default=dict, verbose_name='主机标签')),
                ('connection_type', models.CharField(default='ssh', max_length=20, verbose_name='连接类型')),
                ('become_method', models.CharField(blank=True, default='sudo', max_length=20, verbose_name='提权方式')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '非活跃'), ('failed', '连接失败'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='状态')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='最后检查时间')),
                ('check_message', models.TextField(blank=True, verbose_name='检查信息')),
                ('os_family', models.CharField(blank=True, max_length=50, verbose_name='操作系统家族')),
                ('os_distribution', models.CharField(blank=True, max_length=100, verbose_name='操作系统发行版')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='操作系统版本')),
                ('ansible_facts', models.JSONField(default=dict, verbose_name='Ansible Facts')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'Ansible主机',
                'verbose_name_plural': 'Ansible主机',
                'db_table': 'ansible_host',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='AnsibleHostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='组名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('variables', models.JSONField(default=dict, verbose_name='组变量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ansible_integration.ansiblehostgroup', verbose_name='父组')),
            ],
            options={
                'verbose_name': 'Ansible主机组',
                'verbose_name_plural': 'Ansible主机组',
                'db_table': 'ansible_host_group',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ansibleinventory',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, verbose_name='文件校验和'),
        ),
        migrations.AddField(
            model_name='ansibleinventory',
            name='dynamic_script',
            field=models.TextField(blank=True, verbose_name='动态脚本'),
        ),
        migrations.AddField(
            model_name='ansibleinventory',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='文件路径'),
        ),
        migrations.AddField(
            model_name='ansibleinventory',
            name='git_branch',
            field=models.CharField(default='main', max_length=100, verbose_name='Git分支'),
        ),
        migrations.AddField(
            model_name='ansibleinventory',
            name='git_url',
            field=models.URLField(blank=True, verbose_name='Git仓库URL'),
        ),
        migrations.AddField(
            model_name='ansibleinventory',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='是否已验证'),
        ),
        migrations.AddField(
            model_name='ansibleinventory',
            name='source_type',
            field=models.CharField(choices=[('manual', '手动输入'), ('file', '文件上传'), ('git', 'Git仓库'), ('dynamic', '动态Inventory')], default='manual', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AddField(
            model_name='ansibleinventory',
            name='validation_message',
            field=models.TextField(blank=True, verbose_name='验证信息'),
        ),
        migrations.AddField(
            model_name='ansibleinventory',
            name='version',
            field=models.CharField(default='1.0', max_length=50, verbose_name='版本号'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='ansible_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ansible版本要求'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, verbose_name='内容校验和'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='default_vars',
            field=models.JSONField(default=dict, verbose_name='默认变量'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='execution_count',
            field=models.IntegerField(default=0, verbose_name='执行次数'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='文件路径'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='git_branch',
            field=models.CharField(default='main', max_length=100, verbose_name='Git分支'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='git_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Git中的路径'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='git_url',
            field=models.URLField(blank=True, verbose_name='Git仓库URL'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='是否已验证'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='last_executed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='required_collections',
            field=models.JSONField(default=list, verbose_name='需要的Collection'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='required_roles',
            field=models.JSONField(default=list, verbose_name='需要的Role'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='required_vars',
            field=models.JSONField(default=list, verbose_name='必需变量'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='source_type',
            field=models.CharField(choices=[('manual', '手动创建'), ('file', '文件上传'), ('git', 'Git仓库'), ('template', '模板克隆')], default='manual', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='success_count',
            field=models.IntegerField(default=0, verbose_name='成功次数'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='syntax_check_passed',
            field=models.BooleanField(default=False, verbose_name='语法检查通过'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='validation_message',
            field=models.TextField(blank=True, verbose_name='验证信息'),
        ),
        migrations.AlterField(
            model_name='ansibleplaybook',
            name='category',
            field=models.CharField(choices=[('web', 'Web应用'), ('database', '数据库'), ('monitoring', '监控'), ('security', '安全'), ('networking', '网络'), ('system', '系统'), ('container', '容器部署'), ('cloud', '云服务'), ('other', '其他')], default='other', max_length=50, verbose_name='分类'),
        ),
        migrations.CreateModel(
            name='AnsibleHostGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables', models.JSONField(default=dict, verbose_name='主机变量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_integration.ansiblehostgroup', verbose_name='主机组')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_integration.ansiblehost', verbose_name='主机')),
            ],
            options={
                'verbose_name': '主机组成员关系',
                'verbose_name_plural': '主机组成员关系',
                'db_table': 'ansible_host_group_membership',
                'unique_together': {('host', 'group')},
            },
        ),
        migrations.AddField(
            model_name='ansiblehost',
            name='groups',
            field=models.ManyToManyField(through='ansible_integration.AnsibleHostGroupMembership', to='ansible_integration.ansiblehostgroup', verbose_name='主机组'),
        ),
        migrations.CreateModel(
            name='AnsiblePlaybookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('content', models.TextField(verbose_name='内容快照')),
                ('checksum', models.CharField(max_length=64, verbose_name='内容校验和')),
                ('changelog', models.TextField(blank=True, verbose_name='变更说明')),
                ('is_release', models.BooleanField(default=False, verbose_name='是否为发布版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ansible_integration.ansibleplaybook', verbose_name='Playbook')),
            ],
            options={
                'verbose_name': 'Playbook版本',
                'verbose_name_plural': 'Playbook版本历史',
                'db_table': 'ansible_playbook_version',
                'ordering': ['-created_at'],
                'unique_together': {('playbook', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AnsibleInventoryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('content', models.TextField(verbose_name='内容快照')),
                ('checksum', models.CharField(max_length=64, verbose_name='内容校验和')),
                ('changelog', models.TextField(blank=True, verbose_name='变更说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ansible_integration.ansibleinventory', verbose_name='主机清单')),
            ],
            options={
                'verbose_name': 'Inventory版本',
                'verbose_name_plural': 'Inventory版本历史',
                'db_table': 'ansible_inventory_version',
                'ordering': ['-created_at'],
                'unique_together': {('inventory', 'version')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ansiblehost',
            unique_together={('hostname', 'ip_address')},
        ),
    ]
