# Generated by Django 4.2.23 on 2025-08-01 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_integration', '0002_add_host_credentials'),
        ('ansible_integration', '0003_ansiblehost_ansiblehostgroup_and_more'),
    ]

    operations = [
    ]
