# Generated by Django 4.2.23 on 2025-08-01 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_integration', '0004_merge_20250801_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(help_text='主机在inventory文件中的名称，可能与hostname不同', max_length=100, verbose_name='在清单中的名称')),
                ('host_variables', models.JSONField(default=dict, help_text='在inventory中为该主机定义的变量', verbose_name='主机级别变量')),
                ('is_active', models.BooleanField(default=True, help_text='该主机是否在inventory中激活', verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_integration.ansiblehost', verbose_name='主机')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_integration.ansibleinventory', verbose_name='主机清单')),
            ],
            options={
                'verbose_name': 'Inventory主机关联',
                'verbose_name_plural': 'Inventory主机关联',
                'db_table': 'ansible_inventory_host',
                'ordering': ['inventory', 'inventory_name'],
                'unique_together': {('inventory', 'host')},
            },
        ),
        migrations.AddField(
            model_name='ansibleinventory',
            name='hosts',
            field=models.ManyToManyField(blank=True, help_text='该清单中包含的主机', through='ansible_integration.InventoryHost', to='ansible_integration.ansiblehost', verbose_name='关联主机'),
        ),
    ]
