# Generated by Django 4.2.23 on 2025-07-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dockerimageversion',
            old_name='image_size',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='dockercontainer',
            name='container_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='容器ID'),
        ),
        migrations.AlterField(
            model_name='dockerimage',
            name='image_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='镜像ID'),
        ),
        migrations.AlterField(
            model_name='dockerimageversion',
            name='docker_image_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='镜像ID'),
        ),
    ]
