# Generated by Django 4.2.23 on 2025-07-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_integration', '0002_rename_image_size_dockerimageversion_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerregistry',
            name='project_name',
            field=models.CharField(blank=True, help_text='Harbor等私有仓库的项目名称，如果为空则直接使用镜像名', max_length=100, verbose_name='项目名称'),
        ),
    ]
