# Generated by Django 4.2.23 on 2025-07-22 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docker_integration', '0003_add_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerregistry',
            name='project_name',
            field=models.CharField(blank=True, help_text='此字段已废弃，请使用项目管理功能', max_length=100, verbose_name='项目名称（已废弃）'),
        ),
        migrations.CreateModel(
            name='DockerRegistryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认项目')),
                ('config', models.JSONField(default=dict, verbose_name='项目配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='docker_integration.dockerregistry', verbose_name='所属注册表')),
            ],
            options={
                'verbose_name': 'Docker注册表项目',
                'verbose_name_plural': 'Docker注册表项目',
                'db_table': 'docker_registry_project',
                'ordering': ['name'],
                'unique_together': {('name', 'registry')},
            },
        ),
    ]
