# Generated by Django 4.2.23 on 2025-07-31 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docker_integration', '0004_alter_dockerregistry_project_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockerregistry',
            name='project_name',
        ),
    ]
