# Generated by Django 4.2.23 on 2025-08-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogSyncPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='服务名称', max_length=100, unique=True)),
                ('redis_stream_id', models.CharField(help_text='Redis Stream消息ID', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': '日志同步位置',
                'verbose_name_plural': '日志同步位置',
                'db_table': 'log_sync_position',
            },
        ),
        migrations.CreateModel(
            name='UnifiedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(help_text='唯一日志ID', max_length=255, unique=True)),
                ('timestamp', models.DateTimeField(help_text='日志时间戳')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], help_text='日志级别', max_length=20)),
                ('service', models.CharField(help_text='服务名称', max_length=50)),
                ('component', models.CharField(blank=True, help_text='组件名称', max_length=100, null=True)),
                ('module', models.CharField(blank=True, help_text='模块名称', max_length=100, null=True)),
                ('message', models.TextField(help_text='日志消息')),
                ('execution_id', models.IntegerField(blank=True, help_text='执行ID', null=True)),
                ('trace_id', models.CharField(blank=True, help_text='追踪ID', max_length=100, null=True)),
                ('extra_data', models.JSONField(blank=True, help_text='额外数据', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'verbose_name': '统一日志',
                'verbose_name_plural': '统一日志',
                'db_table': 'unified_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='idx_unified_logs_timestamp'), models.Index(fields=['service'], name='idx_unified_logs_service'), models.Index(fields=['level'], name='idx_unified_logs_level'), models.Index(fields=['execution_id'], name='idx_unified_logs_execution_id'), models.Index(fields=['trace_id'], name='idx_unified_logs_trace_id')],
            },
        ),
    ]
