apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.50.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      customQueryParameters: ''
      manageAlerts: true
      alertmanagerUid: alertmanager
    uid: prometheus
    
  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    isDefault: false
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true
    uid: alertmanager
