# Generated by Django 5.0.0 on 2025-07-16 00:00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicd_integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicstep',
            name='parallel_group',
            field=models.CharField(blank=True, help_text='并行执行组名称', max_length=100),
        ),
    ]
