# Generated by Django 4.2.23 on 2025-06-26 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_auto_20250625_1159'),
        ('cicd_integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicstep',
            name='config',
            field=models.JSONField(default=dict, help_text='步骤配置'),
        ),
        migrations.AddField(
            model_name='atomicstep',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='执行顺序'),
        ),
        migrations.AddField(
            model_name='atomicstep',
            name='pipeline',
            field=models.ForeignKey(blank=True, help_text='所属流水线', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atomic_steps', to='pipelines.pipeline'),
        ),
        migrations.AddField(
            model_name='atomicstep',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='重试次数'),
        ),
        migrations.AddField(
            model_name='atomicstep',
            name='timeout',
            field=models.PositiveIntegerField(default=600, help_text='超时时间(秒)'),
        ),
        migrations.RemoveField(
            model_name='atomicstep',
            name='dependencies',
        ),
        migrations.AddField(
            model_name='atomicstep',
            name='dependencies',
            field=models.JSONField(default=list, help_text='依赖的步骤名称列表'),
        ),
    ]
