# Generated by Django 4.2.23 on 2025-06-26 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicd_integrations', '0002_atomicstep_config_atomicstep_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pipelineexecution',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pipelineexecution',
            name='cicd_tool',
            field=models.ForeignKey(blank=True, help_text='关联的CI/CD工具，为空表示本地执行', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='cicd_integrations.cicdtool'),
        ),
    ]
