# Generated by Django 4.2.23 on 2025-06-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicd_integrations', '0003_alter_pipelineexecution_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicstep',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否激活'),
        ),
    ]
