# Generated by Django 4.2.23 on 2025-06-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicd_integrations', '0004_atomicstep_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicdtool',
            name='description',
            field=models.TextField(blank=True, help_text='工具描述'),
        ),
    ]
