# Generated by Django 4.2.23 on 2025-07-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicd_integrations', '0005_cicdtool_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineexecution',
            name='external_id',
            field=models.CharField(blank=True, help_text='外部工具中的执行ID', max_length=255),
        ),
    ]
