# Generated by Django 4.2.23 on 2025-07-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicd_integrations', '0006_alter_pipelineexecution_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cicdtool',
            name='status',
            field=models.CharField(choices=[('authenticated', 'Authenticated'), ('needs_auth', 'Needs Authentication'), ('offline', 'Offline'), ('unknown', 'Unknown'), ('error', 'Error'), ('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
