# Generated by Django 4.2.23 on 2025-07-02 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cicd_integrations', '0007_alter_cicdtool_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='凭据名称')),
                ('platform', models.CharField(choices=[('gitlab', 'GitLab'), ('github', 'GitHub'), ('gitee', 'Gitee'), ('bitbucket', 'Bitbucket'), ('azure_devops', 'Azure DevOps'), ('custom', '自定义Git服务')], max_length=20, verbose_name='Git平台')),
                ('credential_type', models.CharField(choices=[('username_password', '用户名密码'), ('ssh_key', 'SSH密钥'), ('access_token', '访问令牌'), ('oauth', 'OAuth认证')], max_length=20, verbose_name='认证类型')),
                ('server_url', models.URLField(help_text='如: https://gitlab.company.com', verbose_name='服务器地址')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='用户名')),
                ('password_encrypted', models.TextField(blank=True, verbose_name='加密后的密码/Token')),
                ('ssh_private_key_encrypted', models.TextField(blank=True, verbose_name='加密后的SSH私钥')),
                ('ssh_public_key', models.TextField(blank=True, verbose_name='SSH公钥')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True, verbose_name='上次测试时间')),
                ('last_test_result', models.BooleanField(blank=True, null=True, verbose_name='上次测试结果')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'Git认证凭据',
                'verbose_name_plural': 'Git认证凭据',
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.AddField(
            model_name='atomicstep',
            name='git_credential',
            field=models.ForeignKey(blank=True, help_text='代码拉取步骤使用的Git认证凭据', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cicd_integrations.gitcredential'),
        ),
    ]
