# Generated by Django 4.2.23 on 2025-07-04 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_integration', '0002_ansibleexecution_pipeline_and_more'),
        ('cicd_integrations', '0008_gitcredential_atomicstep_git_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicstep',
            name='ansible_credential',
            field=models.ForeignKey(blank=True, help_text='Ansible步骤使用的SSH认证凭据', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ansible_integration.ansiblecredential'),
        ),
        migrations.AddField(
            model_name='atomicstep',
            name='ansible_inventory',
            field=models.ForeignKey(blank=True, help_text='Ansible步骤使用的Inventory', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ansible_integration.ansibleinventory'),
        ),
        migrations.AddField(
            model_name='atomicstep',
            name='ansible_playbook',
            field=models.ForeignKey(blank=True, help_text='Ansible步骤使用的Playbook', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ansible_integration.ansibleplaybook'),
        ),
        migrations.AlterField(
            model_name='atomicstep',
            name='step_type',
            field=models.CharField(choices=[('fetch_code', 'Fetch Code'), ('build', 'Build'), ('test', 'Test'), ('security_scan', 'Security Scan'), ('deploy', 'Deploy'), ('ansible', 'Ansible Automation'), ('notify', 'Notify'), ('custom', 'Custom')], help_text='步骤类型', max_length=50),
        ),
    ]
