# Generated by Django 4.2.23 on 2025-07-15 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0011_pipelinestep_docker_config_pipelinestep_docker_image_and_more'),
        ('cicd_integrations', '0009_atomicstep_ansible_credential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepexecution',
            name='pipeline_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='pipelines.pipelinestep'),
        ),
        migrations.AlterField(
            model_name='cicdtool',
            name='tool_type',
            field=models.CharField(choices=[('jenkins', 'Jenkins'), ('gitlab_ci', 'GitLab CI'), ('circleci', 'CircleCI'), ('github_actions', 'GitHub Actions'), ('azure_devops', 'Azure DevOps'), ('local', 'Local Executor'), ('custom', 'Custom Tool')], help_text='工具类型', max_length=50),
        ),
        migrations.AlterField(
            model_name='stepexecution',
            name='atomic_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='cicd_integrations.atomicstep'),
        ),
    ]
