# Generated by Django 4.2.23 on 2025-07-16 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cicd_integrations', '0002_add_parallel_group_to_atomic_step'),
        ('cicd_integrations', '0010_stepexecution_pipeline_step_alter_cicdtool_tool_type_and_more'),
    ]

    operations = [
    ]
