# Generated by Django 4.2.23 on 2025-07-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicd_integrations', '0011_merge_20250716_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomicstep',
            name='step_type',
            field=models.CharField(choices=[('fetch_code', 'Fetch Code'), ('build', 'Build'), ('test', 'Test'), ('security_scan', 'Security Scan'), ('deploy', 'Deploy'), ('ansible', 'Ansible Automation'), ('notify', 'Notify'), ('custom', 'Custom'), ('docker_build', 'Docker Build'), ('docker_run', 'Docker Run'), ('docker_push', 'Docker Push'), ('docker_pull', 'Docker Pull'), ('k8s_deploy', 'Kubernetes Deploy'), ('k8s_scale', 'Kubernetes Scale'), ('k8s_delete', 'Kubernetes Delete'), ('k8s_wait', 'Kubernetes Wait'), ('k8s_exec', 'Kubernetes Exec'), ('k8s_logs', 'Kubernetes Logs'), ('approval', 'Approval'), ('shell_script', 'Shell Script')], help_text='步骤类型', max_length=50),
        ),
    ]
