# Generated by Django 4.2.23 on 2025-06-25 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
    ]
