# Generated by Django 4.2.23 on 2025-06-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_auto_20250625_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the pipeline is active'),
        ),
    ]
