# Generated by Django 4.2.23 on 2025-06-30 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicd_integrations', '0004_atomicstep_is_active'),
        ('pipelines', '0003_pipeline_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='execution_mode',
            field=models.CharField(choices=[('local', 'Local Execution'), ('remote', 'Remote Tool'), ('hybrid', 'Hybrid')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='execution_tool',
            field=models.ForeignKey(blank=True, help_text='执行此流水线的CI/CD工具', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='cicd_integrations.cicdtool'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='tool_job_config',
            field=models.JSONField(default=dict, help_text='工具特定的作业配置'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='tool_job_name',
            field=models.CharField(blank=True, help_text='在CI/CD工具中对应的作业名称', max_length=255),
        ),
        migrations.CreateModel(
            name='PipelineToolMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_job_id', models.CharField(help_text='在外部工具中的作业ID', max_length=255)),
                ('external_job_name', models.CharField(help_text='在外部工具中的作业名称', max_length=255)),
                ('auto_sync', models.BooleanField(default=True, help_text='是否自动同步状态')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool_mapping', to='pipelines.pipeline')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_mappings', to='cicd_integrations.cicdtool')),
            ],
            options={
                'verbose_name': 'Pipeline Tool Mapping',
                'verbose_name_plural': 'Pipeline Tool Mappings',
                'unique_together': {('pipeline', 'tool')},
            },
        ),
    ]
