# Generated by Django 4.2.23 on 2025-07-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0009_add_advanced_workflow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stepexecutionhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
