# Generated by Django 4.2.23 on 2025-07-09 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubernetes_integration', '0001_initial'),
        ('docker_integration', '0001_initial'),
        ('pipelines', '0010_alter_approvalrequest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestep',
            name='docker_config',
            field=models.JSONField(default=dict, help_text='Docker-specific configuration (dockerfile path, build args, etc.)'),
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='docker_image',
            field=models.CharField(blank=True, help_text='Docker image name for docker step types', max_length=255),
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='docker_registry',
            field=models.ForeignKey(blank=True, help_text='Docker registry for push/pull operations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_steps', to='docker_integration.dockerregistry'),
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='docker_tag',
            field=models.CharField(blank=True, help_text='Docker image tag', max_length=100),
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='k8s_cluster',
            field=models.ForeignKey(blank=True, help_text='Kubernetes cluster for k8s step types', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_steps', to='kubernetes_integration.kubernetescluster'),
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='k8s_config',
            field=models.JSONField(default=dict, help_text='Kubernetes-specific configuration (deployment spec, wait conditions, etc.)'),
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='k8s_namespace',
            field=models.CharField(blank=True, help_text='Kubernetes namespace', max_length=100),
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='k8s_resource_name',
            field=models.CharField(blank=True, help_text='Kubernetes resource name (deployment, service, etc.)', max_length=255),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='step_type',
            field=models.CharField(choices=[('fetch_code', 'Code Fetch'), ('build', 'Build'), ('test', 'Test Execution'), ('security_scan', 'Security Scan'), ('deploy', 'Deployment'), ('ansible', 'Ansible Playbook'), ('notify', 'Notification'), ('custom', 'Custom Step'), ('script', 'Script Execution'), ('docker_build', 'Docker Build'), ('docker_run', 'Docker Run'), ('docker_push', 'Docker Push'), ('docker_pull', 'Docker Pull'), ('k8s_deploy', 'Kubernetes Deploy'), ('k8s_scale', 'Kubernetes Scale'), ('k8s_delete', 'Kubernetes Delete'), ('k8s_wait', 'Kubernetes Wait'), ('k8s_exec', 'Kubernetes Exec'), ('k8s_logs', 'Kubernetes Logs')], default='custom', help_text='Type of step to execute', max_length=20),
        ),
    ]
