# Generated by Django 4.2.23 on 2025-07-22 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docker_integration', '0004_alter_dockerregistry_project_name_and_more'),
        ('pipelines', '0011_pipelinestep_docker_config_pipelinestep_docker_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestep',
            name='docker_project',
            field=models.ForeignKey(blank=True, help_text='Docker registry project for push/pull operations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_steps', to='docker_integration.dockerregistryproject'),
        ),
    ]
