# Generated by Django 4.2.23 on 2025-08-01 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0012_pipelinestep_docker_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinestep',
            name='docker_project',
        ),
    ]
